### ISSUE TITLE
Sitemap preview does not work: resource not available

### ISSUE THREAD

**Issue by nanosonde** [openhab/openhab-vscode#109]
The sitemap preview does not work in 0.4.0.

### Expected Behavior
A click on the openHAB2 icon opens the sitemap preview in basicui mode since basicui is set as preview mode.

### Current Behavior

When clicking on the openHAB2 icon in the right-top corner it gives the error message:
"home cannot be opened: resource is not available"

"home" is the name of the sitemap: home.sitemap

### Further infos

The debug console gives: 
```
textModelResolverService.ts:88 Unable to open 'openHAB://search?%7B%22hostname%22%3A%22http%3A%2F%2F192.168.10.13%3A8080%22%2C%22route%22%3A%22%2Fbasicui%2Fapp%3Fsitemap%3Dhome%22%7D' resource is not available.
```

The decoded URL looks like this:

`openHAB://search?{"hostname":"http://192.168.10.13:8080","route":"/basicui/app?sitemap=home"}`

When calling the URL http://192.168.10.13:8080/basicui/app?sitemap=home manually in the browser, the correct sitemap is shown in basicui.

### Your Environment
openHAB2:

- openHAB2 2.3.0-1
- OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
- Raspbian GNU/Linux 9.4 (stretch)

VSCode:

- Windows 10pro 64 (1803), VSCode 1.25.1

**Comment by Confectrician** [comment]
Adressed in #117
