### ISSUE TITLE
Quick search in openHAB docs does no longer work

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-vscode#115]
Since the new design of the openHAB website and the documentation pages, the quick search command ("search in openHAB docs") does no longer work.

**Comment by Confectrician** [comment]
It seems that implementing the algolia search isn't that easy, since there is no query or something similiar.

I will ask in the website repo for help and guidance.

**Comment by Confectrician** [comment]
Ok this will be the next function, we will have to remove for now.

Answer from the corresponding website repo issue:
>I don't think there's an easy solution for this right now...
