### ISSUE TITLE
Style guide and Linting

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-vscode#12]
Hey @kubawolanin,
this might be a bit early in the process but will be important soon. Which style guide are you following while implementing snippets, code completion and so on? There are currently no defined style guides for openHAB config files or naming schemes for variables/Items/Groups/... Any opinion?

**Comment by kubawolanin** [comment]
> Which style guide are you following while implementing snippets, code completion and so on?

Just a default formatter implemented in VSCode. Although we might look at solutions like http://editorconfig.org/ to have it aligned for all users :)

**Comment by MHerbst** [comment]
If you add LSP support then, in my opinion, it would be the best to use the language server to format source codes.

**Comment by Confectrician** [comment]
Currently leaving up formatting to openHAB Alignemnt tool.
https://github.com/openhab/openhab-vscode/pull/242/commits/4de81ca8256c625d268f4aecc717399826f25c9c
