### ISSUE TITLE
Add newlines to newly inserted items 

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-vscode#121]
If you use the functions "Create items from channels" (for Things) resp. "Insert into Sitemap" (for Items) the new definitions are pasted into the .items resp. .sitemap files without a newline at the end of the definition.
If you want to insert multiple items (one after the other) you always have click into the text editor and press the return key to get a new line before you insert a new item. 
This is quite annoying if you want to insert multiple items.

Therefore I would like to have an option where you specify whether a newline should be inserted automatically or not.

**Comment by Confectrician** [comment]
Good point.

Additionally we have #47 which needs to have some newline attention too.
I didn't investigate time yet, but this could maybe solved in the same code parts.

**Comment by MHerbst** [comment]
I did not have a look #47 yet. But I agree, that the implementation could be quite similar.

**Comment by zbot473** [comment]
It's actually really simple. I just needed to add a single \n

**Comment by kubawolanin** [comment]
Closed with #136
