### ISSUE TITLE
webview fails to show anything after changing host & password of my pi

### ISSUE THREAD

**Issue by ktownsend-personal** [openhab/openhab-vscode#135]
This extension was operating as expected, but after I changed my OpenHAB hostname and password and then edited the config for the extension accordingly the webview no longer appears. All I get is a blank tab. The sidebar things & items are working just fine, so I assume the REST API is functioning correctly with the new host & password. 

I noticed in the VSCode "Log (Window)" there is an error that seems to occur the first time I open a file that engages the extension (like a .sitemap or .group file). Presumably this is during the extension startup.

[2019-01-23 18:47:07.073] [renderer1] [error] Internal error.: Error: Internal error.
	at new ResponseError (...\.vscode\extensions\openhab.openhab-0.4.1\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
	at handleResponse (...\.vscode\extensions\openhab.openhab-0.4.1\node_modules\vscode-jsonrpc\lib\main.js:430:48)
	at processMessageQueue (...\.vscode\extensions\openhab.openhab-0.4.1\node_modules\vscode-jsonrpc\lib\main.js:258:17)
	at Immediate._onImmediate (...\.vscode\extensions\openhab.openhab-0.4.1\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:789:20)
	at tryOnImmediate (timers.js:751:5)
	at processImmediate [as _immediateCallback] (timers.js:722:5)

Nothing really useful in that message for me. It doesn't give any clues as to what callback generated the error. 

In an attempt to troubleshoot further, I put a logging statement in Utils.js to see what URL was going to be fetched by the webview and that URL is correct; I pasted it into my browser and it worked fine. The webview tab, however, still remains blank. I'm guessing something related to that error when the extension starts up is critical to this feature operating correctly. 

Uninstalling & re-installing the extension didn't fix it either.

Any ideas?

**Comment by SamuelBrucksch** [comment]
Do you use https with your new hostname or still plain http?

**Comment by SamuelBrucksch** [comment]
Thanks, just wanted to make sure. We had some trouble with https in some other areas...

Did you have a pw configured before or was it blank earlier when it worked?

**Comment by ktownsend-cbre** [comment]
@Confectrician, I can't really say because I switched to Home Assistant a while back. I was evaluating both platforms at the time, and HA has been a better experience than OpenHAB so I stuck with it. Neither are perfect, but HA has been easier to research answers, more frequently updated and easier to configure.

**Comment by Confectrician** [comment]
Thanks for you quick response @ktownsend-personal.
Nice to hear, that you made some progress for yourself and found a reliable solution for your needs. :)

I will then close this issue for now, since we are not able to evaluate it this way.
