### ISSUE TITLE
No default settings. Installation problem?

### ISSUE THREAD

**Issue by Gibber** [openhab/openhab-vscode#137]

**Comment by Gibber** [comment]
I just installed Visual Studio Code 1.32.3 and the OpenHAB extension 0.4.1 on a Windows 10 PC. I noticed after the install of the extension that I was not asked to "reload" as the directions indicated I should be. There was no "reload" button. I just closed and restarted Visual Studio and it showed the extension as installed and enabled. I checked the path setting and Visual Studio was added to my environment user variables. 

Now when I open Visual Studio Code settings to change the OpenHAB host address I see lots of default settings but when I search for OpenHAB settings I do not see any default settings for OpenHAB and my only option is to "edit in settings.json". Is this how it is supposed to work now?

**Comment by SamuelBrucksch** [comment]
> Now when I open Visual Studio Code settings to change the OpenHAB host address I see lots of default settings but when I search for OpenHAB settings I do not see any default settings for OpenHAB and my only option is to "edit in settings.json". Is this how it is supposed to work now?

If you press 'F1' and then enter 'Open Settings (UI)' you can search for openhab and will see the default params. If you want to modify them you can click on 'edit in settings.json' and it will copy over the settings and then you can modify them.

**Comment by Gibber** [comment]
Thanks for the response but I don't see what you say I should see.
I press F1, enter "Open Settings (UI)", the only item in the selection list is "Preferences: Open Settings (UI)". If I click on that and enter "openhab" in the search settings, I see:
![openhab settings 1](https://user-images.githubusercontent.com/431797/55253671-98a42680-521b-11e9-9c94-8f73a2aabf49.jpg)
 I don't see default params unless you mean for example the 5007 under lsp port settings.
If I click on "edit in settings.json" I see: 

![openhab settings 2](https://user-images.githubusercontent.com/431797/55253705-a8bc0600-521b-11e9-943f-789017eb5439.jpg)
Still no defaults.
After checking the VS documentation I tried ticking the "open default settings" option under user settings, workbench, settings editor.  Now I get:
![openhab settings 3](https://user-images.githubusercontent.com/431797/55253756-cbe6b580-521b-11e9-93f0-95f9885f5c0a.jpg)

It shows the defaults but it shows the entire 544 settings list and I don't see any way to search it for openhab.

**Comment by Confectrician** [comment]
Sorry for the delay.

There is another setting available in the `Settings Editor` area.
![image](https://user-images.githubusercontent.com/7161177/58355774-be455900-7e75-11e9-8d49-65d59223d219.png)


This will bring you to a split view with some logic included.
You can search for settings and even move them to your custom settings area with a click.

![image](https://user-images.githubusercontent.com/7161177/58355845-fcdb1380-7e75-11e9-8ad3-978f6a66eb55.png)
