### ISSUE TITLE
VSCode and LSP does mark errors in 2.5.0.M2/M3

### ISSUE THREAD

**Issue by lukicsl** [openhab/openhab-vscode#141]
I migrated my 2.4.0 production docker installation to 2.5.0.M2. 
I realized that from that point on VSCode did not mark error in rule file.
I created on my test system 2 empty docker installations with 2.4.0, 2.5.0.M2, 2.5.0.M3.
I edited a simple "test.rules" file with a rule containing errors (missing items)
On version 2.4.0.
![image](https://user-images.githubusercontent.com/23736716/64783090-258f3200-d567-11e9-87c5-076bbefca76e.png)
on versions 2.5.0.M2/M3:
![image](https://user-images.githubusercontent.com/23736716/64783244-9fbfb680-d567-11e9-90f5-aa5b8b9542ad.png)
and all version following workspace setting:
![image](https://user-images.githubusercontent.com/23736716/64783320-cd0c6480-d567-11e9-9fc9-1966dba71134.png)
I set the debug to trace
`
log:set TRACE org.eclipse.smarthome.model.lsp 
log:tail
14:23:26.905 [INFO ] [del.core.internal.ModelRepositoryImpl] - Refreshing model 'test.rules'
14:23:33.330 [DEBUG] [rthome.model.lsp.internal.ModelServer] - Going to wait for a client to connect
14:23:33.332 [DEBUG] [rthome.model.lsp.internal.ModelServer] - Client /192.168.3.41:63511 connected
`

**Comment by Confectrician** [comment]
Would make sense to me, yes.
Please mention me over there so I can subscribe and follow that issue. :)

We can leave this one open and see if there is something to do from vscode side.

**Comment by lukicsl** [comment]
> Would make sense to me, yes.
> Please mention me over there so I can subscribe and follow that issue. :)

No movement on issue 1030, would it be polite to ask somebody directly there, and who.

**Comment by Confectrician** [comment]
I didn't expect any movement that fast to be honest.
LSP is a topic that was introduced by a few people and not so many have a deep knowledge about it.

I have tried todig into this topi too, but it is not that self explaining (at least to me).
I know that this is not the answer you would love to hear now, but i can't do much at that topic currently.

I am back from vacation and will try to push some things forward now, but cant promise anything.

**Comment by lukicsl** [comment]
Thanks, I plan to move to new JSR232, Jython, but still, have a lot of old-style rules.
btw. Is there any special support in VSC planned for JSR 232, Jython?

**Comment by Confectrician** [comment]
I would love to see support for it. :)
I wanted to contribute something over there too but didn't had time yet.

**Comment by Confectrician** [comment]
I am optimistic now and will close this one since openhab/openhab-core/#1171 has been merged. 🙂 
Hopefully this should solve the problem in upcoming milestones.
