### ISSUE TITLE
Update pullapprove to version 3 api

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-vscode#151]
Pullapprove provides a new api version in which the yaml confic changed significantly.
We should migrate to version 3 api config and remove the sign-off part.

Sign off is done through DCO bot anyways already.

**Comment by kaikreuzer** [comment]
What do we use Pullapprove for? I only remember that we used it for sign-off checks before switching to DCO.

**Comment by Confectrician** [comment]
From the current settings it is used for sign-off process and approving via comment.
We could also remove it, but i wanted to check the capabilities first.

It can also do some auto answering on specific conditions.
If there's nothing from interst after reaserch, i would remove it.

**Comment by kaikreuzer** [comment]
> If there's nothing from interst after reaserch, i would remove it.

Afair, that was the outcome the last time someone looked into it. But feel free to check, if you find anything useful :-) .

**Comment by Confectrician** [comment]
After a short look i would go for a removal too. :)
Some of the features could be interesting, but not for this small repo with that few maintainers.
