### ISSUE TITLE
Syntax highlighting is case-sensitive and causes inconsistent view (tested for items files)

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-vscode#17]
## Expected Behavior
All items should look the same way, when they are syntax highlighted and set up correct within the file.

## Current Behavior
Currently item-names get a highlighing, when they start with an upper case letter,
but not when they start with an lower case letter.

![image](https://user-images.githubusercontent.com/7161177/27545794-10ee8484-5a91-11e7-8250-ecc35806722d.png)

**Comment by ThomDietrich** [comment]
I've seen the same behavior with the syntax highlighting available for vim. @kubawolanin this might be related to #12.

**Comment by SamuelBrucksch** [comment]
I will take over this one.

**Comment by thewilli** [comment]
Might be related: Items containing **only** upercase letters are not highlighted as well:

<img width="182" alt="grafik" src="https://user-images.githubusercontent.com/1206639/51202033-02d84b00-18fe-11e9-8a72-b37787fd8359.png">
