### ISSUE TITLE
BasicUI preview not available

### ISSUE THREAD

**Issue by kewld** [openhab/openhab-vscode#176]
I have provided all the details as required below however I am unable to see the basic ui preview when I click the openhab button. Is there something missing or this feature broken as it is plain simple. 

By the way I am trying this in macOS. 

```
{
    "openhab.host": "192.168.0.120",
    "openhab.username": "openhabian",
    "openhab.password": "openhabian",
    "openhab.sitemapPreviewUI": "basicui",
    "openhab.port": 8080,
    "openhab.remoteLspEnabled":true,
    "openhab.remoteLspPort": 5007,
    "atlascode.jira.workingSite": {
        "baseUrlSuffix": "atlassian.net"
    },
    "yaml.schemas": {
        "file:///Users/.vscode/extensions/atlassian.atlascode-2.1.4/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml"
    },
    "workbench.iconTheme": "openhab"
}
```

<img width="219" alt="Screen Shot 2019-11-11 at 9 14 26 PM" src="https://user-images.githubusercontent.com/1915702/68600784-1c6c0400-04c9-11ea-99bf-f35eb2784231.png">

**Comment by Confectrician** [comment]
Hi,

Have you really configured your environment for basic authentication?

It looks like you have configured the default openhabian credentials

```
"openhab.username": "openhabian",
"openhab.password": "openhabian",
```

for username and password.
If you don't use any additional self configured authentication, those are not needed.

Please try to change the settings to:
```
"openhab.username": "",
"openhab.password": "",
```

If you are using a self configured authentication system i would need some more informations,
but we can talk about that after answering this first attempt.

BR
Jerome

**Comment by Confectrician** [comment]
Reference/Possible Duplicate -> #163

**Comment by kewld** [comment]
Yes you are right Confectrician. I got it working now just by removing all the other parameters.

**Comment by kewld** [comment]
This is not an issue. Has already been discussed in #163

**Comment by Confectrician** [comment]
Glad that we could clarify it. :)
