### ISSUE TITLE
Request items from Rest API after saving an items file

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-vscode#183]
**Is your feature request related to a problem? Please describe.**
Items get loaded on startup currently for the HoverProvider.
After saving new Items, those won't get recognised from the HoverProvider until the next startup of vscode.

**Describe the solution you'd like**
We should add an "onSave" action for items files and reload our known items some time after saving the file.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by JAMESBOWLER** [comment]
I use https://marketplace.visualstudio.com/items?itemName=natqe.reload

**Comment by Confectrician** [comment]
Hey @JAMESBOWLER,

Thanks for the tip.
Anyways i think it would be smoother if we start a refresh on our own, when saving a file.

**Comment by Confectrician** [comment]
Fixed in #189
