### ISSUE TITLE
Publish Extension to cdr's Code-Server marketplace

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-vscode#185]
See community post
https://community.openhab.org/t/tutorial-accessing-vs-code-through-a-browser/89258/6

**Comment by Confectrician** [comment]
I have opened an issue, lets wait for some feedback. :)

**Comment by rkoshak** [comment]
I just installed code-server in a Docker deployment and openHAB was in the list. Looks like they accepted it. It shows version 0.4.0.

![image](https://user-images.githubusercontent.com/6385096/71931021-12c5ec00-315a-11ea-8e72-32e1b3ad06f3.png)

**Comment by Confectrician** [comment]
>It shows version 0.4.0.

Really 0.4.0? We are on 0.6.0

**Comment by hmerk** [comment]
What I wrote, it‘s outdated....
Code-server update to VS Code 1.41 should come soon, changes are merged, only release build is missing. Might be they want to fix some other stuff before release.
@Confectrician when you update to 0.7, you should better give then a hit, even they said there is no need to😉

**Comment by Confectrician** [comment]
>@Confectrician when you update to 0.7, you should better give then a hit, even they said there is no need to😉

I will ping you to check the available versionfor me then. 😝

**Comment by hmerk** [comment]
I subscribed to the release updates, so get informed automatically. You can do the same, press „watch“ on their repo and select „release“. But I can inform you 😉

**Comment by Confectrician** [comment]
I meant the extensions version. :)

I think this is only visible through their marketplace from a live installation.

**Comment by hmerk** [comment]
Ah, gotcha ;-) Will do...

**Comment by rkoshak** [comment]
I can confirm that the version of the extension installed through their extensions marketplace lists version 0.4.0.

![image](https://user-images.githubusercontent.com/6385096/72000464-9cc89000-3200-11ea-99c0-8aa75c259bed.png)

I haven't had a chance to use it yet, I still have to figure out whether I can get an SSHFS extension to work or set up NFS to access code on other machines. If I see anything else weird I'll let you know for sure.

**Comment by hmerk** [comment]
Code-Server 1.141.1 was released 21 hours ago, did not get an information automatically. Will give it a try tomorrow with our extensions....

**Comment by Confectrician** [comment]
Hey @hmerk do you know if updates are arriving frequently in the meantime?
Since there is nothing we can do actively here, i would like to close this issue.

**Comment by hmerk** [comment]
Should now check this repo for updates, so I guess yes. Have not done many with coder since moving to openHAB3....
