### ISSUE TITLE
Item and Thing Type icons are missing!

### ISSUE THREAD

**Issue by JueBag** [openhab/openhab-vscode#186]
I am missing the icons in front of the items and things when displaying them on the lefthand sidebar.
See this screenshot:
![missingIcons](https://user-images.githubusercontent.com/18365158/71779415-c9896700-2fb6-11ea-98b3-99356b35a6df.jpg)
Looking at the examples in the [README](https://github.com/openhab/openhab-vscode/blob/master/README.md) I would expect icons like a folder (for groups) and specific ones for different item types in front of the text.

**Comment by Confectrician** [comment]
Loading is tried, but files are not found.

![image](https://user-images.githubusercontent.com/7161177/71780279-edea4100-2fc0-11ea-9670-5ec697485e0d.png)

**Comment by Confectrician** [comment]
The current master is working fine in debug mode. 🤷‍♂ 

![image](https://user-images.githubusercontent.com/7161177/71780499-913c5580-2fc3-11ea-814d-40efa9978efc.png)

**Comment by Confectrician** [comment]
I have found a possible solution.

This alpha should bring back icons for the things explorer on root level for testing purposes.
[oh_6.0.0_iconfix_alpha.zip](https://github.com/openhab/openhab-vscode/files/4023987/oh_6.0.0_iconfix_alpha.zip)

**Comment by JueBag** [comment]
I might be missing something but ...
Deinstalled the openHAB extension and loaded the "oh_6.0.0_iconfix_alpha.vsix" without any change. I am not certain what is meant by "..on root level..", my error might be there.

**Comment by Confectrician** [comment]
Did you switch it back again to the default design and did it work there too?

Generally a reload is alway useful for getting a fresh and cleared editor.
You can do that easily with `ctrl` + `shift` + `p` for opening the command input and searching for "reload".

**Comment by JueBag** [comment]
Yes, I switched it back to DEFAULT and it works with this as well. 
Did the test on Ubuntu and windows, both the same!

**Comment by Confectrician** [comment]
OK, thanks for the feedback.
I will prepare a fix for all occurences, where icons are generated.

**Comment by JueBag** [comment]
Thanks! Working!
