### ISSUE TITLE
icons for files : rules, scripts, persistance not shown

### ISSUE THREAD

**Issue by VWe1** [openhab/openhab-vscode#198]
Default installed Extension within VS-Code. 

Icons for Folder rules is shown but not for files in the Folder. 
this is true  for rules , persistence and scripts

error is in file openhab-icon-theme.json:
fileextensions not correctly set ( missing) 
should be :
"fileExtensions": {
        "html": "_file_html",
        "png": "_file_icons",
        "svg": "_file_icons",
        "items": "_file_items",
        "cfg": "_file_services",
        "sitemap": "_file_sitemaps",
        "rules": "_file_rules",     ////MISSING
        "script": "_file_script",   ////MISSING
        "persist": "_file_persist",   ////MISSING
        "mp3": "_file_sounds",
        "things": "_file_things",
        "map": "_file_transform",
        "scale": "_file_transform"
    },

and at filedefiniton is for fileextension persistence, while the fodler Name is persistence and the filextension is "persist"

**Comment by Confectrician** [comment]
Thanks for reporting and finding the solution right away. :)

**Comment by VWe1** [comment]
> Thanks for reporting and finding the solution right away. :)

your welcome. :-)

**Comment by Confectrician** [comment]
Already fixed in #205
