### ISSUE TITLE
use custom folder icon for `icons/classic`

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-vscode#206]
I noticed the `icons/classic` folder does not have the custom icon of the `icons` folder.

![image](https://user-images.githubusercontent.com/1270359/82201850-3f0c2900-9901-11ea-9587-8c7365202bff.png)

Since `icons/classic` seems to exist by default, I would suggest to use the custom icon for this folder, too.

If you agree I could extend the `openhab-icon-theme.json` and create a PR.

Like:

```json
    "folderNames": {
        "icons": "_folder_icons",
        "classic": "_folder_icons",


    "folderNamesExpanded": {
        "icons": "_folder_open_icons",
        "classic": "_folder_open_icons",
```

This would apply for all folders named `classic`, no matter the parent fodler..
So I don't know if this would be the best solution.

**Comment by Confectrician** [comment]
Fine for me. :)
Let's go, i will assign you.

**Comment by CWempe** [comment]
Fixed. #207

![image](https://user-images.githubusercontent.com/1270359/83065097-29b29f80-a063-11ea-9e71-05663876db13.png)
