### ISSUE TITLE
Problems never refresh after modification of file.

### ISSUE THREAD

**Issue by psyciknz** [openhab/openhab-vscode#208]
When looking in VSCode the rule file doesn't seem to re-evaluate any issues found after they have been corrected.
![image](https://user-images.githubusercontent.com/5350515/86212256-cc62be80-bbcb-11ea-83fa-5abcdc418a5c.png)

![image](https://user-images.githubusercontent.com/5350515/86212313-e9978d00-bbcb-11ea-93fb-82f05243ca63.png)
This rule I copied from an existing rule, and altered the code.  But now the problems never seem to refresh.  Which means I actually gain very little benefit from using VScode as it doesn't add verification for me.

Or is there a way of forcing validation on the open editor?

## Your Environment

* Version used: openhab 2.5.6 docker, on another machine.
VSCode opening a git repository of the openhab conf folder.
After editing an item, I commit it to git
then Jump on the Openhab machine and perform a git pull.

I do have a rest connection to the openhab server though as it can resolve items for me.   But it doesn't like when I add new items, I'm not sure how to force a refresh of the rest api.

Thats most likely what is causing my validation issues.

(e.g., openhab, vscode and extension versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):  Windows 10.

**Comment by Wikibear** [comment]
LSP works without any problem at Linux OS. Using Mint. Same settings with windows and i get the same issue. Via Windows i don't get any syntax check. I must close VSC and after opening error check working short. I can fix then the errors nothing happens. Problems will not refreshed and won't gone. After restart VSC problems gone. I can remember that this works without problems and after some updates of VSC or openhab it doesn't work again.

**Comment by Wikibear** [comment]
@psyciknz can you check please if it's work now? I doesn't change anything and today it's working again.
