### ISSUE TITLE
Support for VSCodium

### ISSUE THREAD

**Issue by nullket** [openhab/openhab-vscode#211]
**Is your feature request related to a problem? Please describe.**
Instead of VSCode I use [VSCodium](https://github.com/VSCodium/vscodium). It is exactly the same like VSCode (not a fork) but with the telemetry/tracking shut off and the executable licensed as a free and open source product (this is indeed somewhat a question of the personal view of things, but nearly nobody likes tracking and telemetry right?). Even tho the software is the same (except for the telemetry and branding part), due to **legal concerns** VSCodium does not provide direct access to the MS VSCode Marketplace. Instead they have setup their own Marketplace called VSX. 

**Describe the solution you'd like**

I would really like to see the `openhab-vscode` extension in the VSX Marketplace as well. The only thing needed would be the publishing once a version is ready. The process is described [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Describe alternatives you've considered**

As the Software is the same, one can easily download the extension from the MS Marketplace. But this would result in not auto updating the extension.

**Comment by Confectrician** [comment]
Sounds fair.

Automating the release process for visual studio marketplace is also still on the todo list.
Maybe it is possible to integrate this directly, when the pipeline is setup once.

**Comment by Confectrician** [comment]
Here we go.

https://open-vsx.org/extension/openhab/openhab
I have published the last stable release now and i am wating for the namespace validation with clipseFdn/open-vsx.org#277.

I have no Deploy Pipeline set up yet, but this should be pretty straight forward.
I have finally accomplished the release pipeline for the microsoft marketpülace and vsx is pretty simliar.
So we will have automated deploys with a new release too in the future.

**Comment by nullket** [comment]
This is great! Thank you very much. Finally free and open codium with openHAB :)

**Comment by Confectrician** [comment]
We are a verified publisher now on Open VSX.
I will keep this issue open until the build pipeline is configured and running well.

**Comment by Confectrician** [comment]
Publish worked.

![image](https://user-images.githubusercontent.com/7161177/104110139-e0068480-52d4-11eb-8599-b39ddadb22c7.png)

Closing this one now. 🙂
