### ISSUE TITLE
hostname is not used completely (FQDN)

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-vscode#213]
According to  [gabbegubben](https://community.openhab.org/t/vs-code-and-rest-api-hostname-does-not-match-certificates-altnames/109150/2) it looks like the extension only takes the hostname from the `openhab.host` parameter instead of the FQDN.

His example:

```json
{
    "openhab.host": "https://openhab.internal.mydomain.com",
    "openhab.port": 443,
    "openhab.username": "openhab",
    "openhab.password": "supersecretpassword",
    "openhab.useRestApi": true
}
```

The error:

```
Error while connecting to openHAB REST API. Hostname/IP does not match certificate's altnames: Host: openhab. is not in the cert's altnames: DNS:openhab.internal.mydomain.com
```

I have not tested this myself and I do not see any easy explanation for this [here](https://github.com/openhab/openhab-vscode/blob/master/client/src/LanguageClient/RemoteLanguageClientProvider.ts#L20).

**Comment by gabbe** [comment]
Apparently the error message about the certificate not matching the hostname was a red herring due to my request URI being malformed. In my SUPERSECRET password I had characters that needed to be encoded.

I opened a pull request with the fix, please advice if I messed up somehow.
