### ISSUE TITLE
Feedback regarding connection error

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-vscode#22]
Hey @kubawolanin,
I've just installed the latest version of the extension. The first issue I encountered was that the connection status isn't clearly indicated. The reason for that is that my openHAB(ian) system does not have the name "openhabianpi".
After installation of the extension there was no indication if the extension is doing something or if there was an error. The OPENHAB ITEMS pane was empty, pressing the reload button didn't do anything. Somewhere along this path of first usage I'd expect a warning if there is no connection (REST), the same warning could be shown if the connection is interrupted at a later point.

Thanks!

**Comment by kubawolanin** [comment]
Yup, just discovered it as well when I was testing the extension on a fresh machine.
There's [a simple check](https://github.com/openhab/openhab-vscode/blob/master/src/extension.ts#L94 that's validating whether your workspace is in fact openHAB workspace. If it's true, it initiates the ItemsExplorer and the code completions.
I think that short term it would be good to remove default hostname to avoid confusion. @dennisausbremen would you like to take a look at this?

As for the warning message - sure! Simple `window.showInformationMessage('...')` would do.
