### ISSUE TITLE
Remove description in sleep time hover

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-vscode#246]
I think we do not need a description in the hover pop up. (like mentioned in https://github.com/openhab/openhab-vscode/issues/240#issuecomment-802199461)

![image](https://user-images.githubusercontent.com/1270359/111679954-ff181a00-8821-11eb-99b8-d95862bc5e74.png)

We do not have one for the Item state hover... 😉 

![image](https://user-images.githubusercontent.com/1270359/111680106-28d14100-8822-11eb-8302-ee72fe2dab71.png)

**Comment by Confectrician** [comment]
Too late. 😛 

Already solved in #245
