### ISSUE TITLE
"Show in PaperUI" URL hard coded

### ISSUE THREAD

**Issue by kl-git** [openhab/openhab-vscode#29]
using openhab-vscode in Visual Studio Code on Mac works like a charme. Many thanks for this very usefull enhancement to configure openhab config.

Using the extension I ran into an issue using the "Show in PaperUI" function; an HTTP error was displayed. Checking the source I found out, that the wrong URL was called. The following patch fixed the problem for me:

## Possible Solution
`diff --git a/src/extension.ts b/src/extension.ts
index 4874fda..ca6fbb8 100644
--- a/src/extension.ts
+++ b/src/extension.ts
@@ -72,7 +72,7 @@ async function init(context: ExtensionContext, disposables: Disposable[]): Promi
     disposables.push(commands.registerCommand('openhab.command.items.showInPaperUI', (query?) => {
         let param: string = query.name ? query.name : query
         return openUI({
-            route: '/paperui/index.html%23/configuration/item/edit/' + param
+            route: '/ui/index.html%23/configuration/item/edit/' + param
         }, param + ' - Paper UI')
     }))
`
## My Environment
openhab2 v2.0 RC1 - on Ubuntu 17.10

Cheers,

Klaus

**Comment by kubawolanin** [comment]
Thanks for reporting Klaus!
I've raised https://github.com/eclipse/smarthome/issues/3827 to see if we can dynamically determine URL of Paper UI.
Your workaround seems to do its job, however it would break for people with OH 2.1 :thinking: 
I'd say it's a opportunity for you to consider upgrading to 2.1 :wink: 

Cheers

**Comment by kl-git** [comment]
Hi Kuba,

thanks for looking at my issue. Upgrading to 2.1 solved the issue 👍. Thanks for your great work. Keep going.

Cheers, Klaus
