### ISSUE TITLE
Leverage Language Server Protocol (LSP) for Xtend

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-vscode#3]
Details:
https://blogs.itemis.com/en/integrating-xtext-language-support-in-visual-studio-code

VS Code docs on the subject:
https://code.visualstudio.com/docs/extensions/example-language-server

*This issue will be edited with further research information*

**Comment by MHerbst** [comment]
Specification of the LSP Version 3:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

There you can see the available message types.

**Comment by ricadelic** [comment]
Typefox's code example is here: https://github.com/TypeFox/xtext-vscode

**Comment by sjka** [comment]
Fyi, just in case anybody would be looking at this - I have started a branch for an upgrade to xtext 2.12 here:
https://github.com/sjka/smarthome/commit/1fb1d6e8174520c75d2cea37e64f60718042bbe9
It's WIP though - it looks okay on a first quick glance, but I didn't spend much time yet to figure out if really everything is still working as before. In any way, it could be used as a basis...
