### ISSUE TITLE
If there's only one sitemap, open it in Basic UI

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-vscode#38]
Currently if we open Basic UI from within VSCode (Ctrl + Alt + O) and sitemap file is not active, the list of available sitemaps displays in the side view.
It would be good to display the default sitemap or the only one if length of [/rest/sitemaps](http://demo.openhab.org:8080/rest/sitemaps) is equal to 1.

**Comment by Confectrician** [comment]
Yeah there has been a long silence in this issue i know^^
But i had one thing that got me stuck here.

>It would be good to display the default sitemap or the only one if length of /rest/sitemaps is equal to 1.

My current response would be:

```js
[
    {
        name: "MyAwesomeSitemap",
        label: "Awesome is awesome is awesome is awe...",
        ...
    },
    {
        name: "_default",
        label: "Home",
        ...
    }
]
```

So the length would be `2` and i would expect it to be loaded anyway.
(Currently this is the case anyways, since i have configured it this way in PaperUI. But thats not the topic.)

So conclusion for me would be:
```js
length == 1 

OR

length == 2 AND any sitemaps name == "_default"
```

wdyt?

**Comment by ThomDietrich** [comment]
Heyho!
my head is filled with unrelated thoughts and I can't clearly remember.
A long there was a discussion I was involved in, in which Kai and I and a few others discussed the meaning of the `_default` sitemap and wether or not it should be shown in Basic UI or removed or whatever. 

Maybe it's worth to check the esh or distro repo for a related issue.

@kaikreuzer anything you want to add?

**Comment by Confectrician** [comment]
But does that change anything for the showing option?

Currently it is there and i would say that in this case any other sitemap should count as **the only one** when there is no additional custom sitemap.

**Comment by Confectrician** [comment]
>It would still be interesting to link this issue to the other one so that your additional check can be removed at a later point.

Totally agree, lets wait if Kai can remember something about it. :)
