### ISSUE TITLE
"Integration with openHAB REST API" - I dont see Items created in PaperUI

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-vscode#46]
Hi,

Do i expect to see Items generated by PaperUI? Or merely on .items only. Thanks

**Comment by kubawolanin** [comment]
Hey @lsafelix75.
You should see all your openHAB items accessible through REST API.
The endpoint I'm using to fetch them is e.g. http://demo.openhab.org:8080/rest/items

Did you try to refresh the items tree view? 
Please provide steps to reproduce this bug.
