### ISSUE TITLE
File Icon Theme has low res PNG icons

### ISSUE THREAD

**Issue by vandijks** [openhab/openhab-vscode#48]
Hey @kubawolanin,

I selected the OpenHAB File Icon Theme but in my case the icons show up in low resolution. Would it be possible to update to SVG versions?

Thanks! :-)

**Comment by kubawolanin** [comment]
Hey @vandijks!

Sure thing. @claudiospizzi introduced the icons in this PR: https://github.com/openhab/openhab-vscode/pull/21

@claudiospizzi would you like to add SVG icons?

@vandijks as an alternative you can go with [vscode-icons](https://github.com/vscode-icons/vscode-icons) extension. It already has an icon for all openHAB-related files.

Cheers,
Kuba
