### ISSUE TITLE
Implement snippets for Type Conversions

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-vscode#52]
Details: https://community.openhab.org/t/type-conversions/32684

Extend [openhabrules.json](https://github.com/openhab/openhab-vscode/blob/master/snippets/openhabrules.json) with pre-filled type conversion snippets

cc: @rkoshak

**Comment by Confectrician** [comment]
I am not too familiar with those snippets.
Could you please take a look if my changes go in the right direction?

https://github.com/Confectrician/openhab-vscode/tree/feature/52

**Comment by kubawolanin** [comment]
Yup, absolutely!
You can also try them out - see CONTRIBUTING.md for more details on how to run the extension from dev environment locally:)
Great stuff! Thank you for your work!

**Comment by Confectrician** [comment]
Yeah i have read about testing somewhere already.
I will go on with some more snippets this week.

Since "snippets" will be a never ending story anyway (there is always that one missing snippet you need. 😄 ) there is no need to get all of them to work in one run.
wdyt?

**Comment by kubawolanin** [comment]
> there is no need to get all of them to work in one run. wdyt?

Sure thing! That's exactly why I didn't include all "design patterns" there, just a couple of them. ;-)

**Comment by Confectrician** [comment]
According to https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_sharing-your-snippets-in-the-marketplace we should think about dividing the snippets into topic related files for the future.

The openhabrules.json has already 440 lines of code and most snippets are short ones.
thing/item/rule snippets can sorted in a logical way most times.

Wdyt?

**Comment by Confectrician** [comment]
Hey @kubawolanin,

I don't want to annoy you, but i would like to start fruther improvings for the snippets.
If you share your opinion i would start refactoring those files and add some new snippets. :smiley:

**Comment by kubawolanin** [comment]
@Confectrician sorry for late response!
I think it's a good idea. Having little pieces of snippets will be more manageable in the future. Let's split them into logical chunks.

Note that the snippets should be described in package.json as well -> https://github.com/openhab/openhab-vscode/blob/master/package.json#L305

Cheers

**Comment by Confectrician** [comment]
Hi,

thanks for the response.
I will try to get some progress between christmas and new year.

**Comment by Confectrician** [comment]
Initial work is done for a while in #77 and the files are growing from time to time.

So no need to keep this one open. 🙂 
If there are useful/popular additional type conversions, we can add them from community feedback.
