### ISSUE TITLE
Remote connections don't work when opening the "root" of a (network?) drive

### ISSUE THREAD

**Issue by sjka** [openhab/openhab-vscode#62]
I think I at least could track down the problem on _my_ side a little of what I first thought was related to #57: 

Whenever I open the "root" of the samba share directly as a folder (no matter whether it's as `file://10.20.0.15/smarthome` or mapped to a network drive like `file://o:`, then it simply does nothing. As soon as I open a subfolder as the "workspace" in VSCode (i.e. 'file://10.20.0.15/smarthome/conf' or 'file://o:/conf'), then everything works nicely - rest calls go out, items/things are displayed and it starts the LSP connection. 

(Windows 10, VSCode 1.18.1, openHAB extension linked from [the comment in #57](https://github.com/openhab/openhab-vscode/issues/57#issuecomment-346872724)).

**Comment by kubawolanin** [comment]
@sjka 
Hey Simon!
Thanks for reporting the defect with so many details! This led me to a solution really quick.
I was expecting the workspace root to be indeed a 'conf' folder by checking `items` and `rules` folders existence immediatelly after the root! 🙈 

The fix is on the way!
Thanks again.
