### ISSUE TITLE
VS Code says: Please open .sitemap file in the editor to add new snippet.

### ISSUE THREAD

**Issue by DriesA** [openhab/openhab-vscode#63]
Hi,

When I right-click an item and choose "Insert into sitemap", I get the following error:
`Please open .sitemap file in the editor to add new snippet.`
I can say that the .sitemap file is opened and had focus right before I right-click on the item.

The same happens when I select "create a rule" from that context menu. This results in:
`Please open .rules file in the editor to add a new rule.`

I installed VS Code 1.18.1 together with version 0.3.0 of the OH extension on my Windows 10 computer. The conf-folders are available trough samba-shared folders. I also did the user-config (specifying the IP of my OH). My OH is a 2.2 snapshot (build #1096), and is an apt-get install. I'm a new VS Code user, so I can't say when this issue was introduced.

This issue was also logged [in the community](https://community.openhab.org/t/visual-studio-code-openhab-extension/30205/124?u=dries).

Not sure what other information I need to provide, just let me know. Thanks!

**Comment by kubawolanin** [comment]
Hey @DriesA,

Could you  hit `Ctrl + ,` in your VS Code and tell me if your configuration strings are located in **User Settings** or **Workspace Settings**?
It may be worth to move them to user settings and see if the problem goes away 🤔 

Cheers!

**Comment by DriesA** [comment]
Hi,
In workspace settings I have this:
`{
    "openhab.host": "192.168.3.2"
}`
In user settings I have this:
`{
    "window.zoomLevel": 2,
    "window.menuBarVisibility": "default",

  // Specifies the URL or IP address for the openHAB preview. (Use 'localhost' when developing locally)
  "openhab.host": "192.168.3.2",
}`

I guess that's correct, right?

**Comment by Murpher** [comment]
Hi @kubawolanin ,

Fantastic work your doing on this.

I have the same issue when I'm working on my win10 laptop and using shared folder onto my raspberry pi.

What I have found though is if I copy the conf folder from my raspberry pi to the laptop running vs code and open the local folder in vs the "Create Items from Channels", "Insert into sitemap" and so on it does work.

Not sure if works for others but can only assume issue must be when working with remote conf folder

**Comment by liquidshock** [comment]
I can confirm that issue happens for all types (rules, sitemaps) when working on remote configuration via SSH mount on MacOS.

**Comment by jameshiscott** [comment]
I have the same problem, running on windows via a openhabian samba share

**Comment by fab33** [comment]
Same bug here. With sftp access to openhab server (and gvfs). Juste after installing vscode and extension it was working ! but today after a complete restart and exactly same setup I have the same error message.

**Comment by fab33** [comment]
Ok I find the bug. it's related to a dot in the path.
located here : https://github.com/openhab/openhab-vscode/blob/a59a95706f2491f5bc51e4b7bbf1785257b7a5c2/src/ThingsExplorer/ItemsProvider.ts#L79
change to
```
        if (document.fileName.split('.').pop() === 'items') {
```
I don't make a PR for this.

**Comment by kubawolanin** [comment]
@fab33 thanks for finding the root cause!

@jameshiscott @liquidshock @Murpher @DriesA please find packaged extension with the applied fix below:
[openhab-0.3.5.vsix.zip](https://github.com/openhab/openhab-vscode/files/1594523/openhab-0.3.5.vsix.zip)

**Comment by DriesA** [comment]
Works as a charm! Thanks a lot!!

**Comment by jameshiscott** [comment]
Yep that fixed it. Thanks guys

**Comment by bligher** [comment]
I still have the error. I use Windows 10 with openhabian. What have I done wrong?

**Comment by leit512** [comment]
@bligher 
You need to install the fixed version linked above.

The extension on the market place is from 11/25/2017 and does not include the fix.

**Comment by kubawolanin** [comment]
@leit512 @bligher - it's no longer a case :) Your extensions should now update to 0.4.0 🎉
