### ISSUE TITLE
Error with REST connection - problem with retrieving configs from Workspace settings

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-vscode#67]
https://community.openhab.org/t/visual-studio-code-howto-connect-to-rest-api/36900/19

Might be related to #57

**Comment by bennybubble** [comment]
Having the same issue:

Openhab 2.2.0-1, RPI3
VSC on Windows 10

Using http://192.168.2.22:8080/rest/items it does show all items in the browser

Workplace settings:

{
    "terminal.integrated.env.windows": {
        "PATH": "C:\\Users\\xxxxxx\\.platformio\\penv\\Scripts;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\Users\\xxxxxx\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files\\Microsoft VS Code\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\Users\\xxxxxx\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files\\Microsoft VS Code\\bin"
    },
    "openhab.host": "192.168.2.22"
}

**Comment by bennybubble** [comment]
Update : problem solved : CTRL + SHIFT + P (reload window) did the trick ....

**Comment by Confectrician** [comment]
@kubawolanin 
I think this one can be closed or am i wrong?

**Comment by kubawolanin** [comment]
Absolutely, thanks @Confectrician! Resolved with https://github.com/openhab/openhab-vscode/pull/58
