### ISSUE TITLE
Code completion for Items, Things etc.

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-vscode#7]
Looking at the gifs it seems like Items are not yet known by the IDE. That's probably a feature intended. Are you going to add them by scanning the items files? A connection to the REST API would be an interesting approach (to also cover PaperUI generated Items). The connection to the REST API would also be needed for #8

**Comment by kubawolanin** [comment]
There's an entry in my notes that I wanted to move here :)
```
Separate view for all items (leverage REST API?)
```

Eclipse SmartHome Designer has a section with all items listed in a column.

We could create a new vscode view for it when working on openHAB files:
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews

**Comment by kaikreuzer** [comment]
> Eclipse SmartHome Designer has a section with all items listed in a column.

It is not "all" items, it is only items defined in item files - and this is a major issue now that we also have items stored in the database (which were created through Paper UI).
So the only clean way to get the full item list is indeed to use the REST API.

Now I wonder: If we need a connection to the REST API of the runtime for this feature and for #8 and maybe others - wouldn't it make sense to make this the ONLY connection, meaning: not having to rely on a samba share for file access? This is a path that I started in the discussion of https://github.com/eclipse/smarthome/issues/1402.

Would VS Code be able to deal with such "REST-provided resources" or does it require them to be on the local file system (sorry if this goes off-topic, feel free to move it to a new issue)?

**Comment by ThomDietrich** [comment]
Exactly my point. We should try to include the REST API as much as possible :+1: 

The REST API as the ONLY connection sounds interesting and should be considered **in the long run** to include e.g. rules created via the Experimental Rule Engine and whatever else might arise. More important in the moment is probably to get a first working and complete (tbd) feature set into the VS Code editor (and not repeat the errors of the Paper UI and the whole database vs files fiasco...).

> Would VS Code be able to deal with such "REST-provided resources" or does it require them to be on the local file system (sorry if this goes off-topic, feel free to move it to a new issue)?

Far from off topic. This question needs to be answered, without a connection to **some** openHAB interfaces, the editor will not be fun in the long run.

**Comment by MHerbst** [comment]
> wouldn't it make sense to make this the ONLY connection, meaning: not having to rely on a samba share for file access?

@kaikreuzer I absolutely agree. If everything (items, rules, sitemaps and even log information #9) would be accessible via REST API we could also access these information remotely via myopenhab.
