### ISSUE TITLE
Dynamic creation of Items from Things's channels doesn't work

### ISSUE THREAD

**Issue by artur-braga** [openhab/openhab-vscode#70]
When trying to create items from Things, the info message appears: "Please open "*.items" file in the editor to add a new snippet." and nothing is converted.
A file home.items was open in the explorer.

## Expected Behavior

I should get the items in my items file.

## Current Behavior

I only get an info message and nothing is generated

## Possible Solution

ItemsProvider class should be debugged.

## Steps to Reproduce (for Bugs)

1. VS code freshly installed on Windows (Dependencies missing?)
2. Openhab running on Pi 3 Model B
3. openhab conf shared via samba as described in tutorials
4. In .vsconfig (openhab.host and openhab.port give) (should one create a project or open as folder)

## Your Environment

* Operating System and version (Windows 10 <-> Raspbian Jessie)

**Comment by artur-braga** [comment]
Same bug as VS Code says: Please open .sitemap file in the editor to add new snippet. #63 I assume. I will close this one. 

Thank you so much for your work! 
I find the project amazing!

Regards, 
Artur

**Comment by kubawolanin** [comment]
Hey @artur-braga - thank you for finding the relevant issue. 
Cheers!

Duplicate of #63
