### ISSUE TITLE
Beginners documentation requested

### ISSUE THREAD

**Issue by stefaanv** [openhab/openhab-vscode#74]
After reading the openHAB 2.2.0 release post by Kai Kreuzer, I was  curious about the Visual Studio config file extension so I installed Visual Studio Code and the openHAB 0.3.5 extension.
Having read through the readme file, I find the documentation is not supportive enough for beginners.
I set up the "openhab.host" and the "openhab.karafCommand" settings, but it is not clear to me if things are working properly or not.
Some questions 
- Do I still need to set up the Samba on my openHAB server like with the Eclipse RCP "openHAB Designer" ?  Or is the file access handled through the REST protocol ?
- I do see "OPENHAB ITEMS" and "OPENHAB THINGS" in the tree on the left.  Does this mean my setup is OK ?
- How can I quickly open a Karaf window likes shown in the video ?  Is there a magic key combination ?  I only have the option "I:powershell" in the Terminal Window.

**Comment by Confectrician** [comment]
> Do I still need to set up the Samba on my openHAB server like with the Eclipse RCP "openHAB Designer" ? Or is the file access handled through the REST protocol ?

It is handled through the rest protocol.

> I do see "OPENHAB ITEMS" and "OPENHAB THINGS" in the tree on the left. Does this mean my setup is OK ?

Sounds at least good so far.
This means that there is a connection existing and the rest api can be accessed.
So "working at least partly" is the correct definition.
This still doesn't say anything about the status of the Language Server, which runs parallel.

> How can I quickly open a Karaf window likes shown in the video ? Is there a magic key combination ? I only have the option "I:powershell" in the Terminal Window.

You need to open the console through a command.
Press `Strg/Ctrl` + `P` -> The command window opens
Press `>` -> You can search for commands now
If you type in `op` for openHAB now you should already see the command for starting the karaf console.



## General part

You are right. Documentation could be improved and i think there were already discussions about it in the documentation repo.
I will see, where it has gone and maybe push the corresponding issues again. 😃

**Comment by stefaanv** [comment]
When opening a Karaf window, I get "The term 'ssh' is not recognized as the name of a cmdlet" error.  I noticed in the readme I'm supposed to install SSH "on my environment".  I have Bitvise installed on my system, but that seems to be insufficient.  I suppose I need command-line SSH support.  What program do you propose ?

How can I check that VS Code is communicating correctly with the language server ?

**Comment by kubawolanin** [comment]
Hi @stefaanv,

> I suppose I need command-line SSH support. What program do you propose ?

It all depends on the OS you're using. If you are on Win10, you most likely have ssh in place.
I, for one, have installed [Git](https://git-scm.com/) which has ssh client included as well (`C:\Program Files\Git\usr\bin\ssh.exe` is the path).

I've also set up my personal VSCode so it uses Git console (MinGW) instead of the regular bash.
To change your terminal in VSCode simply hit `Ctrl + ,` and add the following config parameter:
```
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
```

Hope that helps!

Regarding the issue itself - if you do feel that the documentation could be improved, take an opportunity and [propose the changes yourself](https://github.com/openhab/openhab-vscode/edit/master/README.md) :-)

Cheers,
Kuba
