### ISSUE TITLE
Plugin does... nothing?

### ISSUE THREAD

**Issue by AndrewMorsillo** [openhab/openhab-vscode#80]
I installed plugin version 0.3.5 from plugins panel on vscode 1.19.0. I restarted vscode. Openhab configuration options show up in settings, I set my openhab host properly. I open my config folder mounted via smb and.... nothing. No items panel, no error messages, simply nothing. My rest api is working fine, http://my-openhab-ip:8080/rest/items lists the correct information.

Am I missing something obvious or is there potentially a bug in the plugin?

**Comment by kubawolanin** [comment]
Hi!
The extension initiates when you open a file with openHAB-related extension - items, rules, sitemap, persist or things.

**Comment by AndrewMorsillo** [comment]
Ah that did it, works fine now. Thanks. I expected it to start up when I opened my openhab directory.
