### ISSUE TITLE
Explorer not working

### ISSUE THREAD

**Issue by maciekish** [openhab/openhab-vscode#81]
## Expected Behavior
Configuring the extension should show items in the explorer.

## Current Behavior
Only "OPEN EDITORS" are shown, no "OPENHAB THINGS" or "OPENHAB ITEMS".

## Steps to Reproduce (for Bugs)
1. Install extension in VSC.
2. Configure:

`{
    "git.ignoreMissingGitWarning": true,
    "files.autoSave": "onFocusChange",
    "extensions.autoUpdate": true,
    "openhab.paperInBrowser": true,
    "openhab.useRestApi": true,
    "openhab.port": 8080,
    "openhab.host": "10.0.1.2",
    "openhab.lspPort": 5007,
    "openhab.lspEnabled": true,
}`

## Notes
I have tested the REST API using curl from another machine (not Openhab) and verified i am able to fetch items without authentication. The extension is installed and enable because i get code completion for example when typing "rule" in VSC.

Example curl response:

`curl -X GET --header "Accept: application/json" "http://10.0.1.2:8080/re>
[{"name":"spizowa","label":"Spiżowa","link":"http://10.0.1.2:8080/rest/sitemaps/spizowa","homepage":{"link":"http://10.0.1.2:8080/rest/sitemaps/spizowa/spizowa","leaf":false,"timeout":false,"widgets":[]}},{"name":"_default","label":"Home","link":"http://10.0.1.2:8080/rest/sitemaps/_default","homepage":{"link":"http://10.0.1.2:8080/rest/sitemaps/_default/_default","leaf":false,"timeout":false,"widgets":[]}}]`

## Your Environment
* Version used: Openhab 2.2.0-release on Ubuntu 16.04 LTS
* Operating System and version: Windows 10

**Comment by Confectrician** [comment]
Hi @maciekish,

Did you just open the config folder of your OH installation?
The add-on is initialized, when you open any file with an openhab extension like `.items` or `.rules`.
If i open at least one openHAB related file i get the items and things areas showed.

Maybe something we should add to the documentation of the add-on in the nearer future.

**Comment by maciekish** [comment]
Opening the `openhab2-conf` folder in VSC did the trick. Putting that in the docs would help a lot! Thanks for the quick response.
