### ISSUE TITLE
What to do after installing the extention

### ISSUE THREAD

**Issue by SakibFarhad** [openhab/openhab-vscode#85]
Hello, 
I am new at openHAB but I am really excited to work using this tool. I want to use it with VS Code, I Installed the extension, after that what to do? How can I Start my development? It would be great if someone can give me a hind,  I also tried this but nothing is making sense. (https://community.openhab.org/t/vs-code-openhab-extension/30205) Thanks in Advance

**Comment by kubawolanin** [comment]
Hi @SakibFarhad,
Please read through the [Beginners Guide](https://docs.openhab.org/tutorials/beginner/sitemap.html). This VSCode extension allows you to work with text files in `/conf/` folder.
