### ISSUE TITLE
Error on start-up

### ISSUE THREAD

**Issue by d-adamson** [openhab/openhab-vscode#86]
- Extension Name: openhab
- Extension Version: 0.3.5
- OS Version: Linux x64 4.13.0-26-generic
- VSCode version: 1.19.2

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 311,
		"activateCallTime": 2,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:openhab"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Internal error, please look at the server's logs."
		}
	]
}
```

**Comment by kubawolanin** [comment]
I believe this bug should be reported in [Eclipse SmartHome](https://github.com/eclipse/smarthome/issues?utf8=✓&q=is%3Aissue+is%3Aopen+LSP) repository. Please take a look if there are any related issues submitted already.

Please remember to provide steps to reproduce this bug.
Also, submit the actual server's logs there, so we can trace what's wrong with the Language Server.
Thank you!
