### ISSUE TITLE
Visual studio code does not detect duplicate item names

### ISSUE THREAD

**Issue by HomeOfSourceCode** [openhab/openhab-vscode#87]
It looks like visual studio code does not check duplicate items.

Visual studio code:
![grafik](https://user-images.githubusercontent.com/33092270/35281801-22565ae4-0054-11e8-98a9-42ff194d4b35.png)

Eclipse SmartHome Designer
![grafik](https://user-images.githubusercontent.com/33092270/35281815-2c096f36-0054-11e8-80d3-5ca5fec64397.png)

**Comment by kubawolanin** [comment]
Hi @HomeOfSourceCode!
Please report this issue on [Eclipse SmartHome repository](https://github.com/eclipse/smarthome/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+LSP). 
This is a feature of the Language Server, that's implemented outside VSCode extension.
Thank you!

**Comment by kaikreuzer** [comment]
@HomeOfSourceCode Please only report it if you can confirm that you are using VS Code with an active and working LSP connection - otherwise it is clear that you won't see this error.
