### ISSUE TITLE
Simplify contributing and code quality with extensions.json

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-vscode#94]
vscode offers a way to store so called "recommended" extensions.
You can install all recommended extension with one task through a popup,
which is displayed after cloning/opening the repo in vscode.

We could add recommended extension for contributing to vscode,
like tslint which i didn't know about until @kubawolanin tolde me about in a pull request conversation.

Further reading:
https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

**Comment by kubawolanin** [comment]
Fantastic idea! 
I was thinking of mentioning [vscode-tree-view](https://devdocs.io/backbone/index#View-extend) extension too, as it's recommended for people using openHAB extension anyway :)

The extensions for contributions are a different beast, though. 
Note that all tools needed for the development are in theory stored in `devDependencies` section in `package.json` file.
So whoever wants to dive into the development, should perofm a `npm i` or `npm install` in the project folder anyway. It then downloads [all the packages in the world](https://img.devrant.com/devrant/rant/r_682640_tmrBS.jpg) to make your development pleasant :-)
